### PR TITLE
updated the documentation to reflect accurate setting

### PR DESCRIPTION
**Pull request by mkinney**
Let me know if you have any questions.

### CODE REVIEW

**Comment by ffrank** [comment]
Hi, thanks for the PR.

This setting is used verbatim in the [settings.py](https://github.com/puppet-community/puppet-module-puppetboard/blob/master/templates/settings.py.erb#L17) template. Are you certain that using bona fide boolean values is sound in this context?

If so, then this should be reflected in the [strings documentation](https://github.com/puppet-community/puppet-module-puppetboard/blob/master/manifests/init.pp#L46-L48) as well.

**Comment by mkinney** [comment]
Puppet wants the value without the quotes. If you see params.pp, it is setting the value to:
  $puppetdb_ssl_verify = false

I have updated the strings documentation above.

Let me know if you have any other questions/comments.

**Comment by ffrank** [comment]
Good point about `params`! So yes, I'm in favor.

Come to think of it, I do have one last wishlist item: Could you add the parameter to the `validate_bool` list in the main class? With that in, this will be good to merge.

**Comment by mkinney** [comment]
Done

**Comment by igalic** [comment]
@mkinney would you very much mind [squashing](https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) those three commits down to one?

(if it's too hard to do, because you started working master, you may consider re-submitting this pr, using the [github flow](https://guides.github.com/introduction/flow/index.html) workflow).

**Pull request closed without merging**
